### ISSUE TITLE
Automatically classify downloaded videos according to channels

### ISSUE THREAD

**Issue by PDSCi996** [wiserain/youtube-dl-server#5]
First of all thank you for your hard work.
I recently used "flexget" to automatically push the videos of the youtube channel to youtube-dl for automatic download. I used your container, which used "YTBDL_O=%(uploader)s/%(title)s.%(ext) s" parameter, the result is automatically downloaded videos. Except that the first video will create a directory according to the channel name, subsequent videos will recreate a new directory named "video ID" and move the newly downloaded video to it, download There will be several directories for a few videos. I want youtube-dl to classify the videos downloaded from the same channel into the same directory named after the channel. Could you tell me where I set it wrong?
sorry to bother you.

**Comment by wiserain** [comment]
Will take a look soon. Please wait.
